# Generated by Django 5.0.6 on 2024-05-14 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_key', models.CharField(max_length=50, unique=True)),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('non_critical', 'Non-Critical'), ('critical', 'Critical'), ('expendable', 'Expendable'), ('diagnostics', 'Diagnostics'), ('consumable', 'Consumable'), ('implants', 'Implants'), ('equipment', 'Equipment')], max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('supplier', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
    ]
